"""Add customer_id and notes to orders

Revision ID: 266616b0d24c
Revises: bf1f48d88adb
Create Date: 2026-08-09 18:42:14.539392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266616b0d24c'
down_revision: Union[str, None] = 'bf1f48d88adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('customer_id', sa.String(length=36), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'customer_id')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    # ### end Alembic commands ###
