"""upgrade_customers_module

Revision ID: bf1f48d88adb
Revises: 24010752e38f
Create Date: 2026-08-09 04:49:22.732534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1f48d88adb'
down_revision: Union[str, None] = '24010752e38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('notes', sa.String(length=1000), nullable=True))
    op.add_column('customers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_customers_business_email', 'customers', ['business_id', 'email'])
    op.drop_constraint(op.f('customers_business_id_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_business_id_fkey'), 'customers', 'businesses', ['business_id'], ['id'])
    op.drop_constraint('uq_customers_business_email', 'customers', type_='unique')
    op.drop_column('customers', 'deleted_at')
    op.drop_column('customers', 'notes')
    # ### end Alembic commands ###
