"""Add multidimensional variants and category images

Revision ID: 32c9f3437266
Revises: 305e70d381fc
Create Date: 2026-08-24 20:59:48.974772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32c9f3437266'
down_revision: Union[str, None] = '305e70d381fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_inventory_business_id'), 'inventory', ['business_id'], unique=False)
    op.create_table_comment(
        'inventory',
        'Product stock levels; available = on_hand - reserved',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_inventory_movements_business'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_product_created'), table_name='inventory_movements')
    op.create_index(op.f('ix_inventory_movements_business_id'), 'inventory_movements', ['business_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_product_id'), 'inventory_movements', ['product_id'], unique=False)
    op.drop_constraint(op.f('uq_newsletter_email'), 'newsletter_subscribers', type_='unique')
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.drop_index(op.f('ix_outbox_pending'), table_name='outbox_events', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_constraint(op.f('fk_payments_business_id'), 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_products_brand_trgm'), table_name='products', postgresql_ops={'brand': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_products_name_trgm'), table_name='products', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_products_sku_trgm'), table_name='products', postgresql_ops={'sku': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_table_comment(
        'products',
        'Catalog products; effective price logic lives in the service layer',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_wishlist_user_id'), table_name='wishlist_items')
    op.create_index(op.f('ix_wishlist_items_user_id'), 'wishlist_items', ['user_id'], unique=False)
    op.drop_constraint(op.f('ck_wishlist_not_self'), 'wishlist_items', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_wishlist_not_self'), 'wishlist_items', 'user_id::text <> product_id::text')
    op.drop_index(op.f('ix_wishlist_items_user_id'), table_name='wishlist_items')
    op.create_index(op.f('ix_wishlist_user_id'), 'wishlist_items', ['user_id'], unique=False)
    op.drop_table_comment(
        'products',
        existing_comment='Catalog products; effective price logic lives in the service layer',
        schema=None
    )
    op.create_index(op.f('ix_products_sku_trgm'), 'products', ['sku'], unique=False, postgresql_ops={'sku': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_products_name_trgm'), 'products', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_products_brand_trgm'), 'products', ['brand'], unique=False, postgresql_ops={'brand': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_foreign_key(op.f('fk_payments_business_id'), 'payments', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_outbox_pending'), 'outbox_events', ['status', 'created_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.create_unique_constraint(op.f('uq_newsletter_email'), 'newsletter_subscribers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_inventory_movements_product_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_business_id'), table_name='inventory_movements')
    op.create_index(op.f('ix_inventory_movements_product_created'), 'inventory_movements', ['product_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_business'), 'inventory_movements', ['business_id'], unique=False)
    op.drop_table_comment(
        'inventory',
        existing_comment='Product stock levels; available = on_hand - reserved',
        schema=None
    )
    op.drop_index(op.f('ix_inventory_business_id'), table_name='inventory')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    # ### end Alembic commands ###
