[alembic]
script_location = db/migrations
file_template = %%(year)d%%(month)02d%%(day)02d_%%(hour)02d%%(minute)02d_%%(rev)s_%%(slug)s
prepend_sys_path = .
sqlalchemy.url = postgresql://user:password@localhost:5432/emivo_db

[logging]
default = INFO
